### ISSUE TITLE
webp images don't work on safari

### ISSUE THREAD

**Issue by craigtsmith** [baobabKoodaa/blog#11]
I was trying to follow your money out of thin air article on safari and was getting super confused by the illustrations / diagrams until I released they were corrupt / not rendering correctly.

**Comment by baobabKoodaa** [comment]
Thanks for reporting this! I believe I have fixed it but I don't have an Apple device to test with. Can you confirm that it works now?

**Comment by craigtsmith** [comment]
It is fixed on Safari now :) Thank you!
