### ISSUE TITLE
Build gets stuck at Generating image thumbnails

### ISSUE THREAD

**Issue by chikoddish** [baobabKoodaa/blog#14]
Hi there, 

When I run **gatsby develop** on my machine build gets stuck on Generating image thumbnails.
This is the result I'm getting.

success open and validate gatsby-configs - 0.135s
success load plugins - 2.795s
warn The Google Analytics plugin requires a tracking ID. Did you mean to
success onPreInit - 0.068s
success initialize cache - 0.077s
success copy gatsby files - 0.109s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a
title in a feed.
This means that the plugin will use the default feed title, which may
not match your use case.
success onPreBootstrap - 0.053s
success createSchemaCustomization - 0.281s
success Checking for changed pages - 0.005s
success source and transform nodes - 0.823s
success building schema - 0.727s
Using environment config: 'development'
warn code block or inline code language not specified in markdown.
info Total nodes: 178, SitePage nodes: 23 (use --verbose for breakdown)
success createPages - 8.331s
success Checking for changed pages - 0.009s
success createPagesStatefully - 0.775s
success update schema - 0.138s
success write out redirect data - 0.029s
success Build manifest and related icons - 0.026s
success onPostBootstrap - 0.166s
info bootstrap finished - 20.358s
success onPreExtractQueries - 0.011s
success extract queries from components - 1.437s
success write out requires - 0.387s
success run static queries - 2.428s - 5/5 2.06/s
success run page queries - 0.913s - 29/29 31.77/s
[======================]   29.273 s 481/482100% Generating image thumbn…

Thank you.

**Comment by baobabKoodaa** [comment]
Hi, did you update the npm packages? This is a known bug on newer versions of Gatsby packages. This repository is using older versions of packages in order to avoid this bug.

**Comment by baobabKoodaa** [comment]
I'm gonna close this for now, but I'd be happy to help if you still have issues running the project.

**Comment by chikoddish** [comment]
Yes, I'm using new Gatsby packages. Thank you for your time.
