### ISSUE TITLE
Use of buggy plugin gatsby-plugin-styled-jsx-postcss

### ISSUE THREAD

**Issue by edmcman** [baobabKoodaa/blog#5]
This project is using `gatsby-plugin-styled-jsx-postcss` which is known to cause lockups in some versions of nodejs and gatsbyjs.  For more information please see this issue: https://github.com/gatsbyjs/gatsby/issues/21885

**Comment by baobabKoodaa** [comment]
Thanks for the reporting this! Are you personally experiencing this issue? I would be happy to work on removing postcss from this project if this issue affects someone.

**Comment by edmcman** [comment]
I have personally experienced this issue, but not in your starter.  It seems that this affected your other starter so you already know about it.  Feel free to close the issue if you want.

**Comment by baobabKoodaa** [comment]
I tried for a few hours to get rid of PostCSS, but everything just breaks and it takes too much time to fix everything :( So I'm gonna stop working on this for now, until someone actually has a problem with it.

**Comment by edmcman** [comment]
I don't know if it helps but I was using postcss for nesting, and I switched to sass instead.

**Comment by baobabKoodaa** [comment]
Maybe I should try that. Thanks!
